image: Visual Studio 2017

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  NUGET_APIKEY:
    secure: tUx7I2So0E8VbuxyJ2nYNkz2ryrcjKOYmTn3O5szPAicQ9+GTCT+ML+BLj6prsp6
  GITHUB_ACCESS_TOKEN:
    secure: as7zGFm/RJCI55uS1pEEUfT9plPrGwYloK0k5E1S48UJ1OZymfPiqfyfdiAyL7uh

build_script:
  - ps: ./build.ps1

artifacts:
  - path: 'artifacts/*.nupkg'